---
# gogs pvc


---
# gogs deploy

---
# gogs service


---
# gogs route


---
# etherpad pvc
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-etherpad
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-storage-provisioner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi




---
# etherpad deploy
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      restartPolicy: Always
      containers:
        - name: etherpad
          image: >- 
            {{ wzh_registry_server }}/docker.io/gogs/gogs:latest
          env:
            - name: key
              value: value
          volumeMounts:
            - mountPath: /opt/etherpad-lite/var
              name: pvc-demo 
      volumes:
        - name: pvc-demo 
          persistentVolumeClaim:
            claimName: pvc-etherpad


--- 
# etherpad service
apiVersion: v1
kind: Service
metadata:
  name: etherpad-service
spec:
  selector:
    app: etherpad
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001

---
# etherpad route
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: etherpad
spec:
  to:
    kind: Service
    name: etherpad-service
  port:
    targetPort: 9001


---
# nexus pvc


---
# nexus deploy


---
# nexus service


---
# nexus route
