kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodejs-10
  labels:
    app.openshift.io/runtime: quarkus
spec:
  tags:
    - name: 'latest'
      from:
        kind: DockerImage
        name: >-
          {{ wzh_registry_server }}/registry.access.redhat.com/ubi8/nodejs-10