kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: openjdk18-openshift
spec:
  tags:
    - name: 'latest'
      from:
        kind: DockerImage
        name: >-
          {{ wzh_registry_server }}/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift