---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: quarkus-stack
  namespace: openshift
spec:
  tags:
  - annotations:
      description: Quarkus stack for Java and CodeReady Workspaces
      iconClass: icon-java
      supports: java
      tags: builder,java
      version: "1.8"
    from:
      kind: DockerImage
      name: {{ wzh_registry_server }}/quay.io/openshiftlabs/cloudnative-workspaces-quarkus:1.8
    name: "1.8"
  - annotations:
      description: Quarkus stack for Java and CodeReady Workspaces
      iconClass: icon-java
      supports: java
      tags: builder,java
      version: "2.1"
    from:
      kind: DockerImage
      name: {{ wzh_registry_server }}/quay.io/openshiftlabs/cloudnative-workspaces-quarkus:2.1
    name: "2.1"
  - annotations:
      description: Quarkus stack for Java and CodeReady Workspaces
      iconClass: icon-java
      supports: java
      tags: builder,java
      version: "wzh7"
    from:
      kind: DockerImage
      name: {{ wzh_registry_server }}/docker.io/wangzheng422/cloudnative-workspaces-quarkus:2020-07-09-1594298495
    name: "wzh7"
  - annotations:
      description: Quarkus stack for Java and CodeReady Workspaces
      iconClass: icon-java
      supports: java
      tags: builder,java
      version: "static-html"
    from:
      kind: DockerImage
      name: {{ wzh_registry_server }}/docker.io/wangzheng422/cloudnative-workspaces-quarkus:static-html-2020-07-13-0427
    name: "static-html"