---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: quarkus-stack
  namespace: openshift
spec:
  tags:
  - annotations:
      description: Quarkus stack for Java and CodeReady Workspaces on OCP 4.5
      iconClass: icon-java
      supports: java
      tags: builder,java
      version: "2.4"
    from:
      kind: DockerImage
      name: {{ wzh_registry_server }}/openshiftlabs/cloudnative-workspaces-quarkus:2.4
    name: "2.4"
  - annotations:
      description: Quarkus stack for Java and CodeReady Workspaces on OCP 4.6
      iconClass: icon-java
      supports: java
      tags: builder,java
      version: "2.4.1"
    from:
      kind: DockerImage
      name: {{ wzh_registry_server }}/openshiftlabs/cloudnative-workspaces-quarkus:2.4.1
    name: "2.4.1"
  - annotations:
      description: Quarkus stack for Java and CodeReady Workspaces on OCP 4.6
      iconClass: icon-java
      supports: java
      tags: builder,java
      version: "2.4.1-wzh"
    from:
      kind: DockerImage
      name: {{ wzh_registry_server }}/wangzheng422/cloudnative-workspaces-quarkus:2.4.1-wzh
    name: "2.4.1-wzh"