kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi-quarkus-native-binary-s2i
  namespace: {{ name }}
  labels:
    app.openshift.io/runtime: quarkus
spec:
  tags:
    - name: '1.0'
      from:
        kind: DockerImage
        name: >-
          {{ wzh_registry_server }}/quarkus/ubi-quarkus-native-binary-s2i:1.0