---

- name: create {{ name }} project for user {{ user }}
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ name }}"

- name: add scc and roles in project {{ name }} for user {{ user }}
  shell: |
    oc adm policy add-scc-to-user anyuid -z default -n {{ name }}
    oc adm policy add-scc-to-user privileged -z default -n {{ name }}
    oc adm policy add-role-to-user admin {{ user }} -n {{ name }}

- name: import image-stream to {{ name }} namespace
  k8s:
    state: present
    namespace: {{ name }}
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./files/openjdk-11-image-stream.yaml
  - ./files/datagrid-image-stream.yaml
  - ./files/mongo-image-stream.yaml
  