---
# Implement your Workload deployment tasks here

- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

- name: Setting up num_users for workshop
  debug:
    msg: "Setting up num_users for workshop num_users = {{ num_users }}"

- name: Setting up module_type for workshop
  debug:
    msg: "Setting up module_type for workshop module_type = {{ module_type }}"

- name: create usernames
  set_fact:
    users: "{{ users | default([]) + ['user'+item | string] }}"
  loop: "{{ range(1,((num_users | int) + 1)) | list }}"

- name: create module list
  set_fact:
    modules: "{{ module_type.split(';') | map('trim') | list }}"

- name: Selected Modules
  debug:
    msg: "selected modules list: {{ modules }}"

# - name: Remove service mesh
#   include_tasks: remove-servicemesh.yaml

# - name: Remove serverless
#   include_tasks: remove-serverless.yaml

# - name: Remove pipelines
#   include_tasks: remove-pipelines.yaml

# - name: Remove jaeger
#   include_tasks: remove-jaeger.yaml

# - name: Remove codeready
#   include_tasks: remove-codeready.yaml

# - name: Remove amqstreams
#   include_tasks: remove-amqstreams.yaml

- name: delete templates from openshift namespace
  command: oc delete -n openshift -f -
  args:
    stdin: "{{ lookup('template', item) }}"
  loop:
    - ./files/coolstore-monolith-binary-build-template.yaml
    - ./files/coolstore-monolith-pipeline-build-template.yaml
    - ./files/ccn-sso74-template.yaml
    - ./files/sso74-image-stream.yaml
  ignore_errors: yes

- name: create usernames
  set_fact:
    users: "{{ users | default([]) + ['user'+item | string] }}"
  loop: "{{ range(1,((num_users | int) + 1)) | list }}"

# - name: remove the knative service
#   shell: >
#     oc delete -n {{ item }}-cloudnativeapps service.serving.knative.dev --all
#   with_list: "{{ users }}"
#   ignore_errors: yes

- name: remove the user Projects
  shell: >
    oc delete project {{ item }}-inventory {{ item }}-catalog 
  with_list: "{{ users }}"
  ignore_errors: yes

- name: delete other projects project
  k8s:
    state: absent
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ item }}"
  loop:
    - jenkins
    - labs-infra
    # - knative-serving
    # - knaitve-sources
    # - knative-eventing
  ignore_errors: yes

# Leave this as the last task in the playbook.
- name: Remove workload tasks complete
  debug:
    msg: "Remove Workload Tasks completed successfully."
  when: not silent|bool
